-- CreateEnum
CREATE TYPE "Role" AS ENUM ('FRONTEND_DEVELOPER', 'BACKEND_DEVELOPER', 'FULLSTACK_DEVELOPER', 'UI_UX_DESIGNER', 'DEVOPS_ENGINEER', 'QA_ENGINEER', 'SECURITY_ENGINEER', 'DATA_SCIENTIST', 'AI_ML_ENGINEER', 'PRODUCT_MANAGER', 'PROJECT_MANAGER', 'TECHNICAL_WRITER', 'CONTENT_CREATOR', 'COMMUNITY_MANAGER', 'STUDENT', 'EDUCATOR', 'FOUNDER', 'IT_SUPPORT', 'BUSINESS_ANALYST', 'SMART_CONTRACT_DEVELOPER', 'BLOCKCHAIN_DEVELOPER', 'WEB3_DEVELOPER', 'SOLIDITY_DEVELOPER', 'DAPP_DEVELOPER', 'TOKENOMICS_SPECIALIST', 'NFT_DEVELOPER', 'DEFI_DEVELOPER', 'WEB3_SECURITY_AUDITOR', 'BLOCKCHAIN_ARCHITECT', 'OTHER');

-- CreateTable
CREATE TABLE "event_registrations" (
    "id" TEXT NOT NULL,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "isCommunityMember" BOOLEAN NOT NULL,
    "role" "Role" NOT NULL,
    "roleOther" TEXT,
    "location" TEXT NOT NULL,
    "locationOther" TEXT,
    "openSourceKnowledge" SMALLINT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "event_registrations_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "event_registrations_email_key" ON "event_registrations"("email");
